name: Deploy to EC2 via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to AWS ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
        aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

    - name: Build Docker image
      run: |
        docker build -t wellnudge-ai .

    - name: Tag image
      run: |
        docker tag wellnudge-ai:latest ${{ secrets.ECR_REPO }}:latest

    - name: Push to ECR
      run: |
        docker push ${{ secrets.ECR_REPO }}:latest

    - name: Run Docker container
      run: |
        docker stop wellnudge || true && docker rm wellnudge || true
        docker pull ${{ secrets.ECR_REPO }}:latest
        docker run -d -p 8080:8080 --name wellnudge ${{ secrets.ECR_REPO }}:latest
